project: tactile_ssl
entity: ap2117-heriot-watt-university
save_dir: ${paths.output_dir}
id: ${hydra:job.id}_${experiment_name} # Pass correct id to resume a run
tags: []
group: ${experiment_name}
notes: ~
